---
name: SecureNote CI Pipeline
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver \
            /usr/local/bin/chromedriver

      - name: Run unit tests
        run: |
          python -m pytest tests/unit/test_unit.py -v

      - name: Run Selenium tests
        run: |
          # Start the app in background and run tests
          python app/app.py &
          sleep 3
          python -m pytest tests/functional/test_functional.py -v --tb=short

      - name: Test report
        run: |
          echo "All tests completed successfully!"
